using Gatherlight.Server.Platform.Kernel.Services;
using Gatherlight.Server.Platform.Site.Services;

namespace Gatherlight.Server.Platform.Agent.Chat.Services;

/// <summary>
/// Generates the runtime files the spawned claude needs inside the data folder:
/// <c>state/settings.chat.json</c> (acceptEdits + the PreToolUse scope-guard hook, passed via
/// --settings on the execute phase — regenerated every boot, it's app state) and
/// <c>.claude/hooks/scope-guard.mjs</c> — the agent's SECURITY jail (reads confined to the data
/// folder, writes to plans/ household/ .claude/, Bash denied git-history/network/inline-eval/crawl/
/// path-escape). Because it's a security boundary (not editable knowledge-base content), it's
/// re-issued whenever its <c>GUARD_VERSION</c> is missing or older than the shipped one, so hardening
/// reaches folders seeded by an earlier build. Out-of-boundary work must route through an MCP tool.
/// </summary>
public sealed class ChatEnvironmentService
{
    private readonly ISiteContext _site;
    private readonly IPlatformContext _platform;
    private readonly GatherlightServerOptions _options;
    private readonly ISiteManifestStore _manifest;

    public ChatEnvironmentService(
        ISiteContext site, IPlatformContext platform, GatherlightServerOptions options, ISiteManifestStore manifest)
    {
        _site = site;
        _platform = platform;
        _options = options;
        _manifest = manifest;
    }

    public string SettingsPath => Path.Combine(_platform.StatePath, "settings.chat.json");
    public string SystemSettingsPath => Path.Combine(_platform.StatePath, "settings.system.json");
    public string McpConfigPath => Path.Combine(_platform.StatePath, "mcp.chat.json");
    public string ScopeGuardPath => Path.Combine(_site.ZhikuPath, "hooks", "scope-guard.mjs");

    /// <summary>Returns the data-root-relative path of the scope guard when it was newly
    /// written (caller commits it to the data repo), else null.</summary>
    public string? EnsureFiles()
    {
        var deny = _manifest.Current.Capabilities.Deny;
        File.WriteAllText(SettingsPath, BuildChatSettings(PlannerGuardCommand, deny));
        // 系统模式 settings: same acceptEdits shape, but the PreToolUse hook is the code repo's tracked
        // system scope guard (deny-list: whole repo except guard/, src/server, settings, .git), referenced
        // absolutely since the run's $CLAUDE_PROJECT_DIR is the code repo. Built from the SAME template with
        // a different guard command — NOT a string.Replace that could silently no-op (and leave system mode
        // running the PLANNER scope) if the settings JSON is ever reformatted.
        var systemGuard = Path.Combine(_options.CodeRootPath, "guard", "system-scope-guard.mjs")
            .Replace('\\', '/');
        File.WriteAllText(SystemSettingsPath, BuildChatSettings($"node \\\"{systemGuard}\\\"", deny));
        // MCP over HTTP from this same server — the spawned agent calls registry tools mid-run.
        File.WriteAllText(McpConfigPath,
            $$"""
            {
              "$comment": "Generated by Gatherlight at startup — do not edit.",
              "mcpServers": {
                "planner-tools": { "type": "http", "url": "http://127.0.0.1:{{_options.Port}}/mcp" }
              }
            }
            """);

        string? created = null;
        if (ShouldReissueGuard(ScopeGuardPath))
        {
            Directory.CreateDirectory(Path.GetDirectoryName(ScopeGuardPath)!);
            File.WriteAllText(ScopeGuardPath, RenderScopeGuard());
            created = ".claude/hooks/scope-guard.mjs";
        }
        return created;
    }

    /// <summary>The guard is generated, not shipped verbatim: its WRITE_DIRS come from the site
    /// manifest's declared record directories (plus .claude), so a site that keeps its artifacts
    /// somewhere else is jailed correctly without editing the guard. PROTECTED stays hardcoded —
    /// a site must not be able to widen its own jail by editing its own manifest. DENIED comes from
    /// the same manifest's capabilities.deny — a tool withheld in the allow-list (BuildChatSettings)
    /// must ALSO be denied here, so re-opening one plane (e.g. hand-editing the generated settings
    /// file) doesn't quietly reopen the other.</summary>
    private string RenderScopeGuard()
    {
        var dirs = _manifest.Current.Records.Concat([".claude"]).Distinct();
        var literal = "[" + string.Join(", ", dirs.Select(d => $"'{d.Replace("'", "\\'")}'")) + "]";
        var deniedLiteral = "[" + string.Join(", ", _manifest.Current.Capabilities.Deny.Select(d => $"'{d.Replace("'", "\\'")}'")) + "]";
        return ScopeGuardMjs.Replace("__WRITE_DIRS__", literal).Replace("__DENIED_TOOLS__", deniedLiteral);
    }

    // The scope guard is a SECURITY boundary, not user content: (re)issue it when missing OR when an
    // older GUARD_VERSION is on disk, so a hardened guard reaches data folders seeded by an earlier
    // build (and a weakened/tampered copy is replaced). Same-version files are left as-is — no
    // spurious data-repo commit. A newer on-disk version (dev ahead of server) is also left alone.
    private static readonly int ShippedGuardVersion = ReadGuardVersion(ScopeGuardMjs);

    private static bool ShouldReissueGuard(string guardPath)
    {
        if (!File.Exists(guardPath)) return true;
        try { return ReadGuardVersion(File.ReadAllText(guardPath)) < ShippedGuardVersion; }
        catch { return true; }
    }

    private static int ReadGuardVersion(string body)
    {
        var m = System.Text.RegularExpressions.Regex.Match(body, @"GUARD_VERSION:\s*(\d+)");
        return m.Success && int.TryParse(m.Groups[1].Value, out var v) ? v : 0;
    }

    // The chat (planner) and 系统模式 settings share ONE template; only the PreToolUse guard command
    // differs. Building both from BuildChatSettings — rather than deriving one from the other via
    // string.Replace — means a reformat can't silently drop the substitution and mis-scope a run.
    private const string PlannerGuardCommand = "node \\\"$CLAUDE_PROJECT_DIR/.claude/hooks/scope-guard.mjs\\\"";

    /// <summary>The CLI built-ins granted to the agent by default — WebFetch among them, which the
    /// scope guard's PreToolUse matcher never intercepted (see RenderScopeGuard's DENIED plane for
    /// the other half of closing that gap).</summary>
    private static readonly string[] BuiltinTools =
        ["Read", "Grep", "Glob", "Edit", "Write", "MultiEdit", "TodoWrite", "WebFetch", "WebSearch", "Skill", "Bash"];

    /// <summary>The tool names the guard's PreToolUse logic actually has something to say about
    /// (path/command inspection). This is the matcher's floor — unchanged from before capabilities.deny
    /// existed, and NOT widened to every tool: the guard already allow()s anything it doesn't
    /// recognise, so matching more would only add dispatch latency to calls the hook has no opinion
    /// on.</summary>
    private static readonly string[] GuardMatchedTools =
        ["Edit", "Write", "MultiEdit", "NotebookEdit", "Bash", "Read", "Grep", "Glob"];

    /// <summary>Emits the fixed allow-list minus anything the site's capabilities.deny withholds
    /// (case-insensitive) — a deny entry must remove a built-in from BOTH this generated allow-list
    /// AND the guard's DENIED check, or it isn't actually denied.</summary>
    private static string BuildChatSettings(string guardCommand, IReadOnlyList<string> deny)
    {
        var allow = BuiltinTools.Where(t => !deny.Any(d => string.Equals(d, t, StringComparison.OrdinalIgnoreCase)));
        var allowJson = string.Join(", ", allow.Select(t => $"\"{t}\""));
        // A denied tool must also be in the SET OF TOOLS THE HOOK FIRES FOR, or the DENIED check
        // added to the guard body is unreachable — the exact gap that left WebFetch's guard-side
        // denial decorative. Serialized via JsonSerializer (not manual quoting) because a denied id
        // is user-controlled (site.json) and Regex.Escape can itself introduce backslashes that need
        // JSON-escaping in turn.
        var matcherJson = System.Text.Json.JsonSerializer.Serialize(BuildGuardMatcher(deny));
        return $$"""
        {
          "$comment": "Generated by Gatherlight at startup — do not edit (changes are overwritten). Isolated Claude Code settings for the chat EXECUTE phase, passed via `claude --settings`. Pre-grants permissions so the headless run never stalls on a prompt; the real safety is (1) the PreToolUse scope-guard hook below and (2) the human plan+diff gates in the server.",
          "permissions": {
            "defaultMode": "acceptEdits",
            "allow": [{{allowJson}}]
          },
          "hooks": {
            "PreToolUse": [
              {
                "matcher": {{matcherJson}},
                "hooks": [
                  {
                    "type": "command",
                    "command": "{{guardCommand}}"
                  }
                ]
              }
            ]
          }
        }
        """;
    }

    /// <summary>GuardMatchedTools plus any capabilities.deny id not already in that set, each
    /// regex-escaped (deny ids come from a user-edited site.json and may contain regex metacharacters
    /// like `.` or `(`), joined into the alternation the PreToolUse hook's "matcher" expects. With
    /// deny: [] this is byte-identical to the pre-deny hardcoded matcher — no regression for a site
    /// that denies nothing.</summary>
    private static string BuildGuardMatcher(IReadOnlyList<string> deny)
    {
        var extra = deny
            .Where(d => !GuardMatchedTools.Contains(d, StringComparer.OrdinalIgnoreCase))
            .Distinct(StringComparer.OrdinalIgnoreCase);
        return string.Join("|", GuardMatchedTools.Concat(extra).Select(System.Text.RegularExpressions.Regex.Escape));
    }

    private const string ScopeGuardMjs = """
        #!/usr/bin/env node
        /**
         * PreToolUse scope guard (v2) for Gatherlight headless PLANNER runs — cwd = the data folder.
         * Registered in state/settings.chat.json.
         *
         * The spawned agent is JAILED to the data folder. Enforced boundaries:
         *   WRITE (Edit/Write/MultiEdit/NotebookEdit)  -> under plans/ household/ .claude/ EXCEPT
         *                                                the PROTECTED set (.claude/hooks/, .claude/settings*.json)
         *   READ  (Read/Grep/Glob)                     -> only inside the data folder
         *   BASH                                       -> not: git-history / delete, network egress,
         *                                                inline code-eval, filesystem crawl, or any
         *                                                path outside the folder (args or redirects)
         *
         * Anything genuinely out-of-boundary (fetch a URL, run a scraper, read a shared resource) MUST
         * go through a server MCP tool -- mediated + auditable -- never raw Bash. Else: silent exit 0.
         *
         * Kept identical to guard/system-scope-guard.mjs except WRITE_DIRS + PROTECTED; e2e suite p24
         * runs both. GUARD_VERSION is the upgrade key: the server re-issues newer logic into an
         * existing data folder (ChatEnvironmentService.EnsureFiles), so hardening reaches old installs.
         *
         * DENIED (v6) closes the exfiltration residual this file used to admit to: WebFetch is granted
         * in state/settings.chat.json but this guard's matcher never intercepted it. A site.json
         * capabilities.deny entry now removes the tool from BOTH the generated allow-list
         * (ChatEnvironmentService.BuildChatSettings) AND here — denying a CLI built-in, not just an
         * MCP tool the guard never saw in the first place.
         */
        // GUARD_VERSION: 6
        import path from 'node:path';

        const WRITE_DIRS = __WRITE_DIRS__;
        const PROTECTED = ['.claude/hooks', '.claude/settings.json', '.claude/settings.local.json'];
        const DENIED = __DENIED_TOOLS__;

        const HISTORY = [
          /\bgit\s+(commit|add|push|reset|restore|checkout|clean|rebase|stash|rm)\b/,
          /\brm\s+-[rf]/, /\bRemove-Item\b/i, /\bdel\s+\/[a-z]/i,
        ];
        const NETWORK = [
          /\bcurl\b/, /\bwget\b/, /\bInvoke-WebRequest\b/i, /(^|[\s;&|(])iwr(\s|$)/i,
          /\bInvoke-RestMethod\b/i, /(^|[\s;&|(])nc(\s|$)/, /\bncat\b/, /\btelnet\b/, /\bssh\b/, /\bscp\b/,
          /\bsftp\b/, /\brsync\b/, /\baria2c?\b/, /(^|[\s;&|(])ftp(\s|$)/,
          /\bgit\s+(clone|fetch|pull|ls-remote|remote)\b/,
          /\bpython3?\b[^;&|\n]*-m\s+(http\.server|SimpleHTTPServer|urllib|webbrowser)\b/i,
        ];
        const EVALS = [
          /\bnode\b[^;&|\n]*?\s-(?:e|-eval)\b/, /\b(python3?|py)\s+-c\b/, /\bperl\s+-e\b/, /\bruby\s+-e\b/,
          /\b(powershell|pwsh)\b[\s\S]*\s-(e|enc|encodedcommand|command)\b/i, /(^|[\s;&|(])eval(\s|$)/,
          /\b(?:ba|z|k|da)?sh\s+-c\b/, /[|]\s*(?:ba|z|k|da)?sh\b/,   // inline shell eval / pipe-to-shell
        ];
        const CRAWL = [
          /(^|[\s;&|(])find\s/, /(^|[\s;&|(])ls\s+-[a-zA-Z]*[Rr]/, /(^|[\s;&|(])dir\b[\s\S]*\/s/i,
          /(^|[\s;&|(])grep\b[^;&|\n]*\s-[a-zA-Z]*[rR]/, /(^|[\s;&|(])(rg|tree)(\s|$)/,
          /\bGet-ChildItem\b[^;&|\n]*-[Rr]ecurse/i, /(^|[\s;&|(])gci\b[^;&|\n]*-[a-zA-Z]*[Rr]\b/i,
        ];
        // Sensitive home/profile vars, braced (${HOME}) or bare ($HOME). `~` is caught in bashEscapes.
        const HOME = /(\$\{?(HOME|USERPROFILE|LOCALAPPDATA|APPDATA|HOMEPATH)\b|\$env:|%(USERPROFILE|LOCALAPPDATA|APPDATA|HOMEPATH|HOME)%)/i;

        function deny(reason) {
          process.stdout.write(JSON.stringify({
            hookSpecificOutput: { hookEventName: 'PreToolUse', permissionDecision: 'deny', permissionDecisionReason: reason },
          }));
          process.exit(0);
        }
        const allow = () => process.exit(0);

        // Normalize a path (relative -> resolved against `root`) to a lowercased, drive-aware slash form
        // so containment is a string-prefix test. Git-bash `/c/x` and Windows `C:\x` both fold to `c:/x`.
        function norm(p, root) {
          let s = String(p).replace(/\\/g, '/').replace(/^\/([A-Za-z])(?=\/|$)/, (_, d) => `${d}:`);
          const abs = /^[A-Za-z]:/.test(s) || s.startsWith('/');
          if (!abs) s = `${String(root).replace(/\\/g, '/')}/${s}`;
          const out = [];
          for (const seg of s.split('/')) {
            if (seg === '' || seg === '.') continue;
            if (seg === '..') out.pop(); else out.push(seg);
          }
          return out.join('/').toLowerCase();
        }
        // Relative path of `p` inside `root`, or null when `p` escapes it.
        function relTo(p, root) {
          const r = norm('.', root);
          const n = norm(p, root);
          if (n === r) return '';
          if (n.startsWith(r + '/')) return n.slice(r.length + 1);
          return null;
        }
        const inside = (p, root) => relTo(p, root) !== null;
        // rel is under any entry of `dirs`. A '' entry means the whole jail; other entries match the
        // dir/file itself or anything beneath it. Shared by the WRITE_DIRS allow-list + PROTECTED deny-list.
        const underAny = (rel, dirs) => dirs.some((d) => d === '' || rel === d || rel.startsWith(d + '/'));

        // Best-effort: does any path-like token in a Bash command point outside the jail? The robust
        // controls are the network/eval denials above + the read/write jail at the tool layer; this
        // catches the common cat/cp/mv/redirect-to-outside cases. An OS-level sandbox is the belt-and-
        // suspenders upgrade, and also what would contain code executed inside an agent-authored script.
        function bashEscapes(command, root) {
          if (HOME.test(command)) return true;
          for (let t of command.split(/[\s;|&()<>]+/)) {
            t = t.replace(/^["']+|["']+$/g, '');
            if (!t || t.startsWith('-')) continue;                    // a flag, not a path
            if (/^[a-z][a-z0-9+.-]*:\/\//i.test(t)) continue;         // URL -- network already denied
            if (t.startsWith('~')) return true;                       // home dir
            if (t === '..') return true;                              // bare `cd ..` climbing out
            if (!/[\/\\]/.test(t) && !/^[A-Za-z]:$/.test(t)) continue; // not path-like
            if (!inside(t, root)) return true;
          }
          return false;
        }

        const chunks = [];
        for await (const c of process.stdin) chunks.push(c);
        let payload;
        try { payload = JSON.parse(Buffer.concat(chunks).toString('utf8') || '{}'); } catch { allow(); }

        const toolName = payload.tool_name ?? '';
        if (DENIED.includes(toolName))
          deny(`Blocked: ${toolName} is not available in this site (denied in site.json).`);
        const toolInput = payload.tool_input ?? {};
        const projectDir = payload.cwd || process.env.CLAUDE_PROJECT_DIR || process.cwd();

        if (toolName === 'Bash') {
          const command = String(toolInput.command ?? '');
          if (HISTORY.some((re) => re.test(command)))
            deny('Blocked: no git-history / destructive commands — the server commits only after you approve the diff.');
          if (NETWORK.some((re) => re.test(command)))
            deny('Blocked: no direct network access from the shell. Use WebFetch / WebSearch, or a server MCP tool for out-of-boundary fetches.');
          if (EVALS.some((re) => re.test(command)))
            deny('Blocked: no inline code-eval (node -e / python -c / sh -c / pipe-to-shell / powershell -Command). Run a committed skill file or use an MCP tool.');
          if (CRAWL.some((re) => re.test(command)))
            deny('Blocked: use Read / Glob / Grep to explore — not Bash crawling (find / ls -R / dir /s).');
          if (bashEscapes(command, projectDir))
            deny('Blocked: this command references a path outside the data folder. The agent is jailed here; use an MCP tool for anything out-of-boundary.');
          allow();
        }

        if (toolName === 'Read' || toolName === 'Grep' || toolName === 'Glob') {
          const p = toolInput.file_path ?? toolInput.path ?? '';     // Grep/Glob path optional (absent = cwd, in jail)
          if (p && !inside(String(p), projectDir))
            deny(`Blocked: reads are limited to the data folder — "${p}" is outside it. Use an MCP tool for out-of-boundary data.`);
          allow();
        }

        if (['Edit', 'Write', 'MultiEdit', 'NotebookEdit'].includes(toolName)) {
          const filePath = toolInput.file_path ?? toolInput.notebook_path ?? toolInput.path ?? '';
          if (!filePath) allow();
          const rel = relTo(filePath, projectDir);
          if (rel === null) deny(`Blocked: ${filePath} is outside the data folder.`);
          if (!underAny(rel, WRITE_DIRS))
            deny(`Blocked: the agent may only edit ${WRITE_DIRS.join(', ')} — not "${rel}".`);
          if (underAny(rel, PROTECTED))
            deny(`Blocked: "${rel}" is a protected, app-managed path (the guard / settings) — not editable.`);
          allow();
        }

        allow();
        """;
}
