using Gatherlight.Server.Modules.Core.Services;

namespace Gatherlight.Server.Modules.Chat.Services;

/// <summary>
/// Generates the runtime files the spawned claude needs inside the data folder:
/// <c>state/settings.chat.json</c> (acceptEdits + the PreToolUse scope-guard hook, passed via
/// --settings on the execute phase — regenerated every boot, it's app state) and
/// <c>.claude/hooks/scope-guard.mjs</c> (written only when missing — it lives in knowledge-base
/// territory where the user may customize; the seeder manages upgrades later).
/// </summary>
public sealed class ChatEnvironmentService
{
    private readonly IDataContext _data;
    private readonly GatherlightServerOptions _options;

    public ChatEnvironmentService(IDataContext data, GatherlightServerOptions options)
    {
        _data = data;
        _options = options;
    }

    public string SettingsPath => Path.Combine(_data.StatePath, "settings.chat.json");
    public string SystemSettingsPath => Path.Combine(_data.StatePath, "settings.system.json");
    public string McpConfigPath => Path.Combine(_data.StatePath, "mcp.chat.json");
    public string ScopeGuardPath => Path.Combine(_data.ZhikuPath, "hooks", "scope-guard.mjs");

    /// <summary>Returns the data-root-relative path of the scope guard when it was newly
    /// written (caller commits it to the data repo), else null.</summary>
    public string? EnsureFiles()
    {
        File.WriteAllText(SettingsPath, SettingsChatJson);
        // 系统模式 settings: same acceptEdits shape, but the PreToolUse hook is the code repo's
        // tracked system scope guard (allow-list src/client only), referenced absolutely since
        // the run's $CLAUDE_PROJECT_DIR is the code repo.
        var systemGuard = Path.Combine(_options.CodeRootPath, "devtools", "scripts", "system-scope-guard.mjs")
            .Replace('\\', '/');
        File.WriteAllText(SystemSettingsPath, SettingsChatJson.Replace(
            "node \\\"$CLAUDE_PROJECT_DIR/.claude/hooks/scope-guard.mjs\\\"",
            $"node \\\"{systemGuard}\\\""));
        // MCP over HTTP from this same server — the spawned agent calls registry tools mid-run.
        File.WriteAllText(McpConfigPath,
            $$"""
            {
              "$comment": "Generated by Gatherlight at startup — do not edit.",
              "mcpServers": {
                "planner-tools": { "type": "http", "url": "http://127.0.0.1:{{_options.Port}}/mcp" }
              }
            }
            """);

        string? created = null;
        if (!File.Exists(ScopeGuardPath))
        {
            Directory.CreateDirectory(Path.GetDirectoryName(ScopeGuardPath)!);
            File.WriteAllText(ScopeGuardPath, ScopeGuardMjs);
            created = ".claude/hooks/scope-guard.mjs";
        }
        return created;
    }

    private const string SettingsChatJson = """
        {
          "$comment": "Generated by Gatherlight at startup — do not edit (changes are overwritten). Isolated Claude Code settings for the chat EXECUTE phase, passed via `claude --settings`. Pre-grants permissions so the headless run never stalls on a prompt; the real safety is (1) the PreToolUse scope-guard hook below and (2) the human plan+diff gates in the server.",
          "permissions": {
            "defaultMode": "acceptEdits",
            "allow": [
              "Read", "Grep", "Glob", "Edit", "Write", "MultiEdit",
              "TodoWrite", "WebFetch", "WebSearch", "Skill", "Bash"
            ]
          },
          "hooks": {
            "PreToolUse": [
              {
                "matcher": "Edit|Write|MultiEdit|NotebookEdit|Bash",
                "hooks": [
                  {
                    "type": "command",
                    "command": "node \"$CLAUDE_PROJECT_DIR/.claude/hooks/scope-guard.mjs\""
                  }
                ]
              }
            ]
          }
        }
        """;

    private const string ScopeGuardMjs = """
        #!/usr/bin/env node
        /**
         * PreToolUse scope guard for Gatherlight's headless claude runs.
         *
         * Registered in state/settings.chat.json. Reads the hook payload on stdin and DENIES:
         *   - Edit/Write/MultiEdit/NotebookEdit whose target path is outside the
         *     allow-list (plans/, household/, .claude/).
         *   - Bash commands that would commit / mutate git history or destroy files
         *     (the SERVER owns commits, only after human diff approval).
         *
         * Anything else: stay silent (exit 0) so the normal acceptEdits flow proceeds.
         */
        import path from 'node:path';

        const ALLOWED_DIRS = ['plans', 'household', '.claude'];

        const FORBIDDEN_BASH = [
          /\bgit\s+commit\b/,
          /\bgit\s+add\b/,
          /\bgit\s+push\b/,
          /\bgit\s+reset\b/,
          /\bgit\s+restore\b/,
          /\bgit\s+checkout\b/,
          /\bgit\s+clean\b/,
          /\bgit\s+rebase\b/,
          /\bgit\s+stash\b/,
          /\bgit\s+rm\b/,
          /\brm\s+-[rf]/,
          /\bRemove-Item\b/i
        ];

        function deny(reason) {
          process.stdout.write(JSON.stringify({
            hookSpecificOutput: {
              hookEventName: 'PreToolUse',
              permissionDecision: 'deny',
              permissionDecisionReason: reason
            }
          }));
          process.exit(0);
        }

        function allowSilently() {
          process.exit(0);
        }

        function isInsideAllowed(relPath) {
          const norm = relPath.split(path.sep).join('/').replace(/^\.\//, '');
          return ALLOWED_DIRS.some((dir) => norm === dir || norm.startsWith(dir + '/'));
        }

        async function readStdin() {
          const chunks = [];
          for await (const chunk of process.stdin) chunks.push(chunk);
          return Buffer.concat(chunks).toString('utf8');
        }

        const raw = await readStdin();
        let payload;
        try {
          payload = JSON.parse(raw || '{}');
        } catch {
          process.stderr.write('[scope-guard] could not parse hook payload\n');
          allowSilently();
        }

        const toolName = payload.tool_name ?? '';
        const toolInput = payload.tool_input ?? {};
        const projectDir = payload.cwd || process.env.CLAUDE_PROJECT_DIR || process.cwd();

        if (toolName === 'Bash') {
          const command = String(toolInput.command ?? '');
          const hit = FORBIDDEN_BASH.find((re) => re.test(command));
          if (hit) {
            deny(
              `Blocked: the chat agent may not run git-history / destructive commands ` +
                `(matched ${hit}). The server commits only after you approve the diff.`
            );
          }
          allowSilently();
        }

        if (['Edit', 'Write', 'MultiEdit', 'NotebookEdit'].includes(toolName)) {
          const filePath = toolInput.file_path ?? toolInput.notebook_path ?? toolInput.path ?? '';
          if (!filePath) allowSilently();

          const abs = path.isAbsolute(filePath) ? filePath : path.resolve(projectDir, filePath);
          const rel = path.relative(projectDir, abs);

          if (rel.startsWith('..') || path.isAbsolute(rel)) {
            deny(`Blocked: ${filePath} is outside the workspace.`);
          }
          if (!isInsideAllowed(rel)) {
            deny(
              `Blocked: the chat agent may only edit ${ALLOWED_DIRS.join(', ')} — ` +
                `not "${rel.split(path.sep).join('/')}".`
            );
          }
          allowSilently();
        }

        allowSilently();
        """;
}
